export const DEFAULT_GENRES = [
  "Alternative",
  "Black Metal",
  "Blues",
  "Death Metal",
  "Doom Metal",
  "Electronic",
  "Experimental",
  "Folk",
  "Hardcore",
  "Hip-hop",
  "Indie",
  "Jazz",
  "Metal",
  "Noise",
  "Post-punk",
  "Post-rock",
  "Punk",
  "Rock",
  "Shoegaze",
  "Thrash Metal",
].sort((a, b) => a.localeCompare(b));
